# action.yml - metadata file for this action
name: 'ROS Release Docker Action'
description: 'Creates ROS release binaries for specified architecture'
inputs:
  ros-distro: #id of input
    description: 'ROS distro for container'
    required: false
    default: 'noetic'
  image: #id of input image
    description: 'Docker Image to use'
    required: false
    default: 'amd64_Dockerfile'
outputs:
  time: #id of output
    description: 'The time we greeted you'
  file: #id of file output
    description: 'The built debian'
runs:
  using: 'docker'
  image: ${{ inputs.image }}
  args:
    - ${{ inputs.ros-distro }}