# action.yml - metadata file for this action
name: 'ROS Release Docker Action'
description: 'Creates ROS release binaries for specified architecture'
inputs:
  ros-distro: #id of input
    description: 'ROS distro for container'
    required: false
    default: 'noetic'
outputs:
  time: #id of output
    description: 'The time we greeted you'
  files: #id of file output
    description: 'The built debian'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ros-distro }}