# This is a basic workflow to help you get started with Actions

name: test-pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-action:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:      
      DOCKER_TARGET_PLATFORM: linux/arm/v8  
    name: Testing this action workflow
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Action
        uses: actions/checkout@v2
      # Use action to test functionality
      - name: Run the action workflow
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          ros-distro: 'noetic'
      # Use output from action 
      - name: Get Action Output
        run: echo "${{ steps.test.outputs.time }}"
